; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	d:\platformer\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\platformergame\src\gameengine\batchedmodel.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	___glewGenBuffers:DWORD
EXTRN	__imp__glDrawElements@16:PROC
EXTRN	___glewBufferData:DWORD
EXTRN	___glewBufferSubData:DWORD
EXTRN	___glewBindBuffer:DWORD
EXTRN	___glewVertexAttribPointer:DWORD
EXTRN	___glewEnableVertexAttribArray:DWORD
END
