; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	d:\platformer\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\platformergame\src\gameengine\light.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??$?4I@?$vec@$02M$0A@@glm@@QAEAAU01@ABU?$vec@$02I$0A@@1@@Z ; glm::vec<3,float,0>::operator=<unsigned int>
PUBLIC	?getColor@Light@@QAE?AU?$vec@$02M$0A@@glm@@XZ	; Light::getColor
PUBLIC	?getPosition@Light@@QAE?AU?$vec@$02M$0A@@glm@@XZ ; Light::getPosition
PUBLIC	?setPosition@Light@@QAEXU?$vec@$02M$0A@@glm@@@Z	; Light::setPosition
PUBLIC	??0Light@@QAE@U?$vec@$02I$0A@@glm@@U?$vec@$02M$0A@@2@@Z ; Light::Light
END
