; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	d:\platformer\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\platformergame\src\gameengine\matrixmath.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_1BHE@MGBAAAOM@?$AAD?$AA?3?$AA?2?$AAP?$AAl?$AAa?$AAt?$AAf?$AAo?$AAr?$AAm?$AAe?$AAr?$AA?2?$AAC@ ; `string'
;	COMDAT ??_C@_1BHE@MGBAAAOM@?$AAD?$AA?3?$AA?2?$AAP?$AAl?$AAa?$AAt?$AAf?$AAo?$AAr?$AAm?$AAe?$AAr?$AA?2?$AAC@
CONST	SEGMENT
??_C@_1BHE@MGBAAAOM@?$AAD?$AA?3?$AA?2?$AAP?$AAl?$AAa?$AAt?$AAf?$AAo?$AAr?$AAm?$AAe?$AAr?$AA?2?$AAC@ DB 'D'
	DB	00H, ':', 00H, '\', 00H, 'P', 00H, 'l', 00H, 'a', 00H, 't', 00H
	DB	'f', 00H, 'o', 00H, 'r', 00H, 'm', 00H, 'e', 00H, 'r', 00H, '\'
	DB	00H, 'C', 00H, 'P', 00H, 'P', 00H, 'G', 00H, 'a', 00H, 'm', 00H
	DB	'e', 00H, '-', 00H, 'a', 00H, '3', 00H, '8', 00H, 'd', 00H, '0'
	DB	00H, 'd', 00H, 'b', 00H, '7', 00H, '2', 00H, '6', 00H, 'a', 00H
	DB	'b', 00H, '2', 00H, 'f', 00H, 'f', 00H, '8', 00H, '9', 00H, 'a'
	DB	00H, 'f', 00H, 'd', 00H, 'd', 00H, '0', 00H, '2', 00H, 'c', 00H
	DB	'1', 00H, '8', 00H, '3', 00H, '9', 00H, '4', 00H, 'b', 00H, 'd'
	DB	00H, '0', 00H, 'c', 00H, '5', 00H, '8', 00H, '3', 00H, '4', 00H
	DB	'0', 00H, 'c', 00H, '9', 00H, '\', 00H, 'C', 00H, 'P', 00H, 'P'
	DB	00H, 'G', 00H, 'a', 00H, 'm', 00H, 'e', 00H, '-', 00H, 'a', 00H
	DB	'3', 00H, '8', 00H, 'd', 00H, '0', 00H, 'd', 00H, 'b', 00H, '7'
	DB	00H, '2', 00H, '6', 00H, 'a', 00H, 'b', 00H, '2', 00H, 'f', 00H
	DB	'f', 00H, '8', 00H, '9', 00H, 'a', 00H, 'f', 00H, 'd', 00H, 'd'
	DB	00H, '0', 00H, '2', 00H, 'c', 00H, '1', 00H, '8', 00H, '3', 00H
	DB	'9', 00H, '4', 00H, 'b', 00H, 'd', 00H, '0', 00H, 'c', 00H, '5'
	DB	00H, '8', 00H, '3', 00H, '4', 00H, '0', 00H, 'c', 00H, '9', 00H
	DB	'\', 00H, 'P', 00H, 'l', 00H, 'a', 00H, 't', 00H, 'f', 00H, 'o'
	DB	00H, 'r', 00H, 'm', 00H, 'e', 00H, 'r', 00H, 'G', 00H, 'a', 00H
	DB	'm', 00H, 'e', 00H, '\', 00H, 's', 00H, 'r', 00H, 'c', 00H, '\'
	DB	00H, 'G', 00H, 'a', 00H, 'm', 00H, 'e', 00H, 'E', 00H, 'n', 00H
	DB	'g', 00H, 'i', 00H, 'n', 00H, 'e', 00H, '\', 00H, 'H', 00H, 'e'
	DB	00H, 'a', 00H, 'd', 00H, 'e', 00H, 'r', 00H, 'F', 00H, 'i', 00H
	DB	'l', 00H, 'e', 00H, 's', 00H, '\', 00H, 'V', 00H, 'e', 00H, 'n'
	DB	00H, 'd', 00H, 'o', 00H, 'r', 00H, '\', 00H, 'g', 00H, 'l', 00H
	DB	'm', 00H, '\', 00H, 'd', 00H, 'e', 00H, 't', 00H, 'a', 00H, 'i'
	DB	00H, 'l', 00H, '\', 00H, 't', 00H, 'y', 00H, 'p', 00H, 'e', 00H
	DB	'_', 00H, 'v', 00H, 'e', 00H, 'c', 00H, '3', 00H, '.', 00H, 'i'
	DB	00H, 'n', 00H, 'l', 00H, 00H, 00H		; `string'
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@ABU10@0@Z	; glm::operator*<float,0>
PUBLIC	??0?$vec@$03M$0A@@glm@@QAE@M@Z			; glm::vec<4,float,0>::vec<4,float,0>
PUBLIC	??0?$vec@$03M$0A@@glm@@QAE@MMMM@Z		; glm::vec<4,float,0>::vec<4,float,0>
PUBLIC	?call@?$compute_vec4_mul@M$0A@$0A@@detail@glm@@SA?AU?$vec@$03M$0A@@3@ABU43@0@Z ; glm::detail::compute_vec4_mul<float,0,0>::call
PUBLIC	?call@?$compute_vec4_add@M$0A@$0A@@detail@glm@@SA?AU?$vec@$03M$0A@@3@ABU43@0@Z ; glm::detail::compute_vec4_add<float,0,0>::call
PUBLIC	?call@?$compute_dot@U?$vec@$02M$0A@@glm@@M$0A@@detail@glm@@SAMABU?$vec@$02M$0A@@3@0@Z ; glm::detail::compute_dot<glm::vec<3,float,0>,float,0>::call
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@ABU10@M@Z	; glm::operator*<float,0>
PUBLIC	??$inversesqrt@M@glm@@YAMM@Z			; glm::inversesqrt<float>
PUBLIC	??$dot@$02M$0A@@glm@@YAMABU?$vec@$02M$0A@@0@0@Z	; glm::dot<3,float,0>
PUBLIC	??$?YM@?$vec@$03M$0A@@glm@@QAEAAU01@ABU01@@Z	; glm::vec<4,float,0>::operator+=<float>
PUBLIC	??$?XM@?$vec@$03M$0A@@glm@@QAEAAU01@M@Z		; glm::vec<4,float,0>::operator*=<float>
PUBLIC	?length@?$vec@$02M$0A@@glm@@SAHXZ		; glm::vec<3,float,0>::length
PUBLIC	?call@?$compute_normalize@$02M$0A@$0A@@detail@glm@@SA?AU?$vec@$02M$0A@@3@ABU43@@Z ; glm::detail::compute_normalize<3,float,0,0>::call
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@MABU10@@Z	; glm::operator*<float,0>
PUBLIC	??$normalize@$02M$0A@@glm@@YA?AU?$vec@$02M$0A@@0@ABU10@@Z ; glm::normalize<3,float,0>
PUBLIC	??$?HM$0A@@glm@@YA?AU?$vec@$03M$0A@@0@ABU10@0@Z	; glm::operator+<float,0>
PUBLIC	??$?DM$0A@@glm@@YA?AU?$vec@$03M$0A@@0@ABU10@ABM@Z ; glm::operator*<float,0>
PUBLIC	??A?$mat@$03$03M$0A@@glm@@QBEABU?$vec@$03M$0A@@1@H@Z ; glm::mat<4,4,float,0>::operator[]
PUBLIC	??0?$vec@$02M$0A@@glm@@QAE@MMM@Z		; glm::vec<3,float,0>::vec<3,float,0>
PUBLIC	??A?$vec@$02M$0A@@glm@@QAEAAMH@Z		; glm::vec<3,float,0>::operator[]
PUBLIC	??A?$vec@$02M$0A@@glm@@QBEABMH@Z		; glm::vec<3,float,0>::operator[]
PUBLIC	??$?GM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@ABU10@@Z	; glm::operator-<float,0>
PUBLIC	??$scale@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@ABU10@ABU?$vec@$02M$0A@@0@@Z ; glm::scale<float,0>
PUBLIC	??$rotate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@ABU10@MABU?$vec@$02M$0A@@0@@Z ; glm::rotate<float,0>
PUBLIC	??$?0HHH@?$vec@$02M$0A@@glm@@QAE@HHH@Z		; glm::vec<3,float,0>::vec<3,float,0><int,int,int>
PUBLIC	??$translate@M$0A@@glm@@YA?AU?$mat@$03$03M$0A@@0@ABU10@ABU?$vec@$02M$0A@@0@@Z ; glm::translate<float,0>
PUBLIC	?sqrt@@YAMM@Z					; sqrt
PUBLIC	?sin@@YAMM@Z					; sin
PUBLIC	?cos@@YAMM@Z					; cos
PUBLIC	_sqrtf
PUBLIC	_sinf
PUBLIC	_cosf
PUBLIC	?getViewMatrix@@YA?AU?$mat@$03$03M$0A@@glm@@U?$vec@$02M$0A@@2@0@Z ; getViewMatrix
PUBLIC	?getmatrix@@YA?AU?$mat@$03$03M$0A@@glm@@U?$vec@$02M$0A@@2@0M@Z ; getmatrix
END
