; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	d:\platformer\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\cppgame-a38d0db726ab2ff89afdd02c18394bd0c58340c9\platformergame\src\gameengine\start.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_08CEDOAIBO@Engine3d@			; `string'
PUBLIC	??_C@_04CBHBHCPO@FPS?$DN@			; `string'
PUBLIC	??_C@_06NHAKHCIK@Shader@			; `string'
PUBLIC	??_C@_0O@NDBNOHJJ@TerrainShader@		; `string'
PUBLIC	??_C@_09MGGOFKHG@texDragon@			; `string'
PUBLIC	??_C@_05JOBLOEL@grass@				; `string'
PUBLIC	??_C@_06OBNGLPMO@dragon@			; `string'
PUBLIC	??_C@_0N@MAPAOIKF@stallTexture@			; `string'
PUBLIC	??_C@_05MEMGOBLF@stall@				; `string'
PUBLIC	??_C@_0L@PPHAJBEH@projection@			; `string'
PUBLIC	??_C@_03EIGHKCEN@rts@				; `string'
PUBLIC	??_C@_07PKJOFHPL@sampler@			; `string'
PUBLIC	??_C@_0O@POHKLELN@LightPosition@		; `string'
PUBLIC	??_C@_0L@HNLDIBIB@lightColor@			; `string'
PUBLIC	??_C@_08HPPOJBLD@haslight@			; `string'
PUBLIC	??_C@_04CHADEDPO@view@				; `string'
PUBLIC	??_C@_06IHEKJFFH@damper@			; `string'
PUBLIC	??_C@_0N@LJNLFOD@reflectivity@			; `string'
PUBLIC	??_C@_09OJHOCBK@heightmap@			; `string'
PUBLIC	?frames@@3HA					; frames
PUBLIC	?lightPosition@@3U?$vec@$02M$0A@@glm@@A		; lightPosition
PUBLIC	?Position@@3U?$vec@$02M$0A@@glm@@A		; Position
PUBLIC	?now@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A ; now
PUBLIC	?CamPosition@@3U?$vec@$02M$0A@@glm@@A		; CamPosition
PUBLIC	?Time2@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A ; Time2
PUBLIC	?DeltaT@@3NA					; DeltaT
PUBLIC	?Time1@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A ; Time1
PUBLIC	?frameTime@@3NA					; frameTime
PUBLIC	?canRender@@3EA					; canRender
PUBLIC	?FPS@@3HA					; FPS
PUBLIC	?timepassed@@3NA				; timepassed
PUBLIC	?fullscreem@@3_NA				; fullscreem
PUBLIC	?lastFrame@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A ; lastFrame
PUBLIC	?framecap@@3NA					; framecap
PUBLIC	?unproccesed@@3NA				; unproccesed
?frames@@3HA DD	01H DUP (?)				; frames
?lightPosition@@3U?$vec@$02M$0A@@glm@@A DB 0cH DUP (?)	; lightPosition
?now@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A DQ 01H DUP (?) ; now
?CamPosition@@3U?$vec@$02M$0A@@glm@@A DB 0cH DUP (?)	; CamPosition
	ALIGN	8

?Time2@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A DQ 01H DUP (?) ; Time2
?DeltaT@@3NA DQ	01H DUP (?)				; DeltaT
?Time1@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A DQ 01H DUP (?) ; Time1
?frameTime@@3NA DQ 01H DUP (?)				; frameTime
?canRender@@3EA DB 01H DUP (?)				; canRender
	ALIGN	4

?FPS@@3HA DD	01H DUP (?)				; FPS
?timepassed@@3NA DQ 01H DUP (?)				; timepassed
?fullscreem@@3_NA DB 01H DUP (?)			; fullscreem
	ALIGN	8

?lastFrame@@3V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@A DQ 01H DUP (?) ; lastFrame
?unproccesed@@3NA DQ 01H DUP (?)			; unproccesed
_BSS	ENDS
;	COMDAT ??_C@_09OJHOCBK@heightmap@
CONST	SEGMENT
??_C@_09OJHOCBK@heightmap@ DB 'heightmap', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@LJNLFOD@reflectivity@
CONST	SEGMENT
??_C@_0N@LJNLFOD@reflectivity@ DB 'reflectivity', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_06IHEKJFFH@damper@
CONST	SEGMENT
??_C@_06IHEKJFFH@damper@ DB 'damper', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04CHADEDPO@view@
CONST	SEGMENT
??_C@_04CHADEDPO@view@ DB 'view', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_08HPPOJBLD@haslight@
CONST	SEGMENT
??_C@_08HPPOJBLD@haslight@ DB 'haslight', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@HNLDIBIB@lightColor@
CONST	SEGMENT
??_C@_0L@HNLDIBIB@lightColor@ DB 'lightColor', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@POHKLELN@LightPosition@
CONST	SEGMENT
??_C@_0O@POHKLELN@LightPosition@ DB 'LightPosition', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_07PKJOFHPL@sampler@
CONST	SEGMENT
??_C@_07PKJOFHPL@sampler@ DB 'sampler', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_03EIGHKCEN@rts@
CONST	SEGMENT
??_C@_03EIGHKCEN@rts@ DB 'rts', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@PPHAJBEH@projection@
CONST	SEGMENT
??_C@_0L@PPHAJBEH@projection@ DB 'projection', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_05MEMGOBLF@stall@
CONST	SEGMENT
??_C@_05MEMGOBLF@stall@ DB 'stall', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@MAPAOIKF@stallTexture@
CONST	SEGMENT
??_C@_0N@MAPAOIKF@stallTexture@ DB 'stallTexture', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_06OBNGLPMO@dragon@
CONST	SEGMENT
??_C@_06OBNGLPMO@dragon@ DB 'dragon', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05JOBLOEL@grass@
CONST	SEGMENT
??_C@_05JOBLOEL@grass@ DB 'grass', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_09MGGOFKHG@texDragon@
CONST	SEGMENT
??_C@_09MGGOFKHG@texDragon@ DB 'texDragon', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@NDBNOHJJ@TerrainShader@
CONST	SEGMENT
??_C@_0O@NDBNOHJJ@TerrainShader@ DB 'TerrainShader', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_06NHAKHCIK@Shader@
CONST	SEGMENT
??_C@_06NHAKHCIK@Shader@ DB 'Shader', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04CBHBHCPO@FPS?$DN@
CONST	SEGMENT
??_C@_04CBHBHCPO@FPS?$DN@ DB 'FPS=', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_08CEDOAIBO@Engine3d@
CONST	SEGMENT
??_C@_08CEDOAIBO@Engine3d@ DB 'Engine3d', 00H		; `string'
?Position@@3U?$vec@$02M$0A@@glm@@A DD 000000000r ; 0	; Position
	DD	000000000r			; 0
	DD	0c1c80000r			; -25
	ORG $+3
?framecap@@3NA DQ 03f91111111111111r		; 0.0166667 ; framecap
PUBLIC	??$?0HMH@?$vec@$02M$0A@@glm@@QAE@HMH@Z		; glm::vec<3,float,0>::vec<3,float,0><int,float,int>
PUBLIC	??$?0MHM@?$vec@$02M$0A@@glm@@QAE@MHM@Z		; glm::vec<3,float,0>::vec<3,float,0><float,int,float>
PUBLIC	??$?0M$0A@@?$vec@$02I$0A@@glm@@QAE@ABU?$vec@$02M$0A@@1@@Z ; glm::vec<3,unsigned int,0>::vec<3,unsigned int,0><float,0>
PUBLIC	?__autoclassinit2@Terrain@@QAEXI@Z		; Terrain::__autoclassinit2
PUBLIC	??1Terrain@@QAE@XZ				; Terrain::~Terrain
PUBLIC	??1Entity@@QAE@XZ				; Entity::~Entity
PUBLIC	?__autoclassinit2@objLoader@@QAEXI@Z		; objLoader::__autoclassinit2
PUBLIC	??1objLoader@@QAE@XZ				; objLoader::~objLoader
PUBLIC	?__autoclassinit2@Texture@@QAEXI@Z		; Texture::__autoclassinit2
PUBLIC	_main
PUBLIC	?intFPS@@YAXXZ					; intFPS
PUBLIC	?fps@@YAXXZ					; fps
PUBLIC	?Input@@YAXVCamera@@@Z				; Input
PUBLIC	?__autoclassinit2@Window@@QAEXI@Z		; Window::__autoclassinit2
PUBLIC	??$?0_JU?$ratio@$00$0DLJKMKAA@@std@@$0A@@?$duration@NU?$ratio@$00$00@std@@@chrono@std@@QAE@ABV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@12@@Z ; std::chrono::duration<double,std::ratio<1,1> >::duration<double,std::ratio<1,1> ><__int64,std::ratio<1,1000000000>,0>
PUBLIC	?window@@3VWindow@@A				; window
?window@@3VWindow@@A DB 018H DUP (?)			; window
_BSS	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$_main DQ 00000002219930522r	; 7.23598e-313
	DD	FLAT:__unwindtable$_main
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000100000000r		; 2.122e-314
	ORG $+4
__unwindtable$_main DD 0ffffffffH
	DD	FLAT:__unwindfunclet$_main$0
	DD	00H
	DD	FLAT:__unwindfunclet$_main$1
	DD	01H
	DD	FLAT:__unwindfunclet$_main$2
	DD	01H
	DD	FLAT:__unwindfunclet$_main$3
	DD	01H
	DD	FLAT:__unwindfunclet$_main$5
	DD	04H
	DD	FLAT:__unwindfunclet$_main$7
	DD	05H
	DD	FLAT:__unwindfunclet$_main$9
	DD	06H
	DD	FLAT:__unwindfunclet$_main$11
	DD	07H
	DD	FLAT:__unwindfunclet$_main$13
	DD	08H
	DD	FLAT:__unwindfunclet$_main$14
	DD	09H
	DD	FLAT:__unwindfunclet$_main$15
	DD	0aH
	DD	FLAT:__unwindfunclet$_main$16
	DD	08H
	DD	FLAT:__unwindfunclet$_main$18
	DD	0cH
	DD	FLAT:__unwindfunclet$_main$19
	DD	0dH
	DD	FLAT:__unwindfunclet$_main$20
	DD	0eH
	DD	FLAT:__unwindfunclet$_main$21
	DD	0cH
	DD	FLAT:__unwindfunclet$_main$23
	DD	010H
	DD	FLAT:__unwindfunclet$_main$24
	DD	011H
	DD	FLAT:__unwindfunclet$_main$25
	DD	012H
	DD	FLAT:__unwindfunclet$_main$26
	DD	012H
	DD	FLAT:__unwindfunclet$_main$42
	DD	014H
	DD	FLAT:__unwindfunclet$_main$43
	DD	015H
	DD	FLAT:__unwindfunclet$_main$44
	DD	016H
	DD	FLAT:__unwindfunclet$_main$45
	DD	012H
	DD	FLAT:__unwindfunclet$_main$28
	DD	018H
	DD	FLAT:__unwindfunclet$_main$29
	DD	019H
	DD	FLAT:__unwindfunclet$_main$30
	DD	019H
	DD	FLAT:___std_terminate
	DD	018H
	DD	FLAT:___std_terminate
	DD	012H
	DD	FLAT:___std_terminate
	DD	011H
	DD	FLAT:___std_terminate
	DD	010H
	DD	FLAT:___std_terminate
	DD	0cH
	DD	FLAT:___std_terminate
	DD	08H
	DD	FLAT:___std_terminate
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1Entity@@QAE@XZ DQ 00000000119930522r ; 2.33398e-314
	DD	FLAT:__unwindtable$??1Entity@@QAE@XZ
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000500000000r		; 1.061e-313
__unwindtable$??1Entity@@QAE@XZ DD 0ffffffffH
	DD	FLAT:___std_terminate
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1Terrain@@QAE@XZ DQ 00000000119930522r ; 2.33398e-314
	DD	FLAT:__unwindtable$??1Terrain@@QAE@XZ
	DQ	00000000000000000r		; 0
	DQ	00000000000000000r		; 0
	DQ	00000000500000000r		; 1.061e-313
__unwindtable$??1Terrain@@QAE@XZ DD 0ffffffffH
	DD	FLAT:___std_terminate
?window$initializer$@@3P6AXXZA DD FLAT:??__Ewindow@@YAXXZ ; window$initializer$
END
